### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nvieirapt** [higuita/vodafone.pt-xmltv#2]
On Ubuntu 18.04

$ ./tv_grab_pt_vdf.sh
awk: line 9: function gensub never defined
awk: line 31: function gensub never defined
awk: line 31: function gensub never defined
awk: line 31: function gensub never defined
awk: line 31: function gensub never defined
awk: line 31: function gensub never defined
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv source-info-url="https://store.services.sapo.pt/en/cat/catalog/other/meo-epg/technical-description" source-info-name="Vodafone EPG Service" generator-info-name="XMLTV/$Id: tv_grab_pt_vodafone,v 1.0 2016/11/15 00:00:00 higuita Exp $" generator-info-url="http://www.xmltv.org/">

</tv>

**Comment by higuita** [comment]
As you closed this, you probably solved already, but if not, i suspect you have nawk installed instead of gnu awk (gawk).
also, this script was a prototype, the real xmltv grabber in perl was build and already merged in master xmltv. Both should work
