### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by be18** [higuita/vodafone.pt-xmltv#3]
Is possible to use the script with option -output?
tks

**Comment by higuita** [comment]
this script is just a temporary fix and guide for [senica](https://github.com/nsenica/xmltv) to port it to perl and push it to xmltv again... but it is easy to add, so: https://github.com/higuita/vodafone.pt-xmltv/commit/f4149e19f7684de03271defe0975715697d5c28c

Just add `-o /tmp/vodafone.xmltv` (and `-d 4` to grab 4 days if needed) 

But remember later to check xmltv for the real xmltv grabber, it will be better than this script
