### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by K-vanc** [higuita/vodafone.pt-xmltv#6]
Hi friend, first of all nice project. I just want to notify you as I used your below channel list file as source for channel creation of my siteconfig and already gave reference to your repo.

https://github.com/higuita/vodafone.pt-xmltv/blob/master/shell/channel.list

https://github.com/K-vanc/Tempest-EPG-Generator/blob/38d99df7faadc18c70bf41926447e65cdb33c94d/Siteconfigs/Portugal/%5BENC%5D%5BEX%5Dvodafone.pt_1.siteconfig.php

so it would be nice if periodically update it with the changes 😄 

Joke aside, keep it up with your nice work

K-vanc

**Comment by higuita** [comment]
Thank you, i didn't knew about your project!, it is interesting!
yes, the idea is to keep that file updated ... and still i'm trying to find a way to get that info by other steps, lets see.

for now, the next step is to port this to perl and update the xmltv project vodafone grabber

**Comment by K-vanc** [comment]
Thanks. Many people doesnt know about my project and there are many people who know and use my project but are not telling anyone, such as some iptv/epg service providers etc. That's why People are still forcefully paying for shitware under name of donation. If you didnt yet, try to check my declaration.md file when you have time so you will understand better😀

Good that you will continue on developing your tool and updating your channel list file. My siteconfig is checking raw of it and parsing with regex as channel id and name. It will continue to work as long as file structure is not changed. If you change the structure(since it is yours, you have totally rights to do it 😀) it is still not a problem, i may update capturing regex patterns easily.

**Comment by higuita** [comment]
The channel.list format should not change, unless vodafone adds more data there that we can't get from any other place... even that, it would be probably just add a new column.

I updated my script to fix/workaround some issues, like bad characters,  some missing epg data and the elements order. Now the file pass the xmltv tv_validate_file test... not sure if you may have this issues, but check anyway

**Comment by K-vanc** [comment]
Well done. 

No, i dont have any issue with xmltv validation or bad encoding at all. I am using mbstring and iconv modules for converting and fixing encoding errors. Also have some other custom solutions for rare cases so i am good with them 😀

**Comment by higuita** [comment]
in my case it was a title with <nap> , that broke the xml, but easy to fix by replacing < with `&lt;`

**Comment by higuita** [comment]
New channels added, after i did a scan for all the IDs and them slowly mapped them... not totally sure for some channels (like some porn ones), but most are for sure correct

**Comment by K-vanc** [comment]
Hi. Thanks for the update. I checked channel generation of my siteconfig and seems all are ok. commented ones also excluded from generation properly so Well done 👍

**Comment by higuita** [comment]
@K-vanc 
Hi there, i have updated the channels.list, mostly vodafone removing a few channels and promoting other to official... and many updated icons
